name: testAndLint

on: push
  
jobs:
  make-lint-and-tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.4'

        - name: Run lint
          run:  make lint

        - name: run test
          run:  make test