name: testAndLint

on: push
  
jobs:
  make-lint-and-tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.4'

        - name: Install
          run: make install

        - name: Run lint
          run:  make lint

        - name: run test
          run:  make test

        - name: publish code coverage
          uses: paambaati/codeclimate-action@v2.6.0
        # Add Code Climate secret key
        env:
          TESTREPORTER_ID: ${{ secrets.TESTREPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          coverageLocations: ${{github.workplace}}/build/logs/clover.xml:clover
          debug: true