name: testAndLint

on: push
  jobs:
    build:
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v2

        - name: Run test & publish code coverage
        - run:  make lint
        - run:  make test
        - uses: paambaati/codeclimate-action@v2.6.0
        # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.TESTREPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          coverageLocations: ${{github.workplace}}/build/logs/clover.xml:clover
          debug: true